# Generated by Django 3.1.2 on 2021-07-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styletransfer', '0002_remove_srcimg_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('input_img_id', models.IntegerField(blank=True, null=True)),
                ('output_img_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StyleImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(blank=True, max_length=125, null=True)),
                ('is_ref', models.BooleanField(blank=True, null=True)),
                ('ref_class', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'style_img',
                'managed': False,
            },
        ),
    ]
