# Generated by Django 3.1.2 on 2021-07-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styletransfer', '0003_job_styleimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(blank=True, max_length=125, null=True)),
            ],
            options={
                'db_table': 'output_img',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='srcimg',
            options={'managed': False},
        ),
    ]
