# Generated by Django 3.1.2 on 2021-07-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styletransfer', '0004_auto_20210708_0248'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='srcimg',
            table='input_img',
        ),
    ]
