# Generated by Django 3.1.2 on 2021-07-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styletransfer', '0005_auto_20210709_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.ImageField(upload_to='images/input/')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'input_img',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SrcImg',
        ),
    ]
