# Generated by Django 3.1.2 on 2021-07-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='option_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='option',
            new_name='option_id',
        ),
        migrations.RemoveField(
            model_name='result',
            name='quesion',
        ),
    ]
