# Generated by Django 3.1.2 on 2021-07-19 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_session_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='option',
            table='option',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
        migrations.AlterModelTable(
            name='result',
            table='result',
        ),
        migrations.AlterModelTable(
            name='session',
            table='session',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
