# Generated by Django 3.1.2 on 2021-07-13 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styletransfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputimg',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='outputimg',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='styleimg',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='inputimg',
            table='input_img',
        ),
        migrations.AlterModelTable(
            name='job',
            table='job',
        ),
        migrations.AlterModelTable(
            name='outputimg',
            table='output_img',
        ),
        migrations.AlterModelTable(
            name='styleimg',
            table='style_img',
        ),
    ]
