# Generated by Django 3.1.2 on 2021-07-13 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styletransfer', '0002_auto_20210713_0736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='model',
            table='model',
        ),
    ]
